version: '3'
services:
  node0:
    image: raft
    environment:
      - ID=0
  node1:
    image: raft
    environment:
      - ID=1
  node2:
    image: raft
    environment:
      - ID=2
  node3:
    image: raft
    environment:
      - ID=3
  node4:
    image: raft
    environment:
      - ID=4
